[package]
name = "minpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
rustyline = "10"
anyhow = "1"
colored = "2"

[dev-dependencies]
test-case = "2.1"
